version: '4'

services:
  obs:
    image: naturalis/waarneming-django-2:0.0.1
    restart: unless-stopped
    environment:
      PYTHON_USER: obs
    volumes:
      - /home/obs/django:/code
      - /home/obs/static:/static
      - /var/uwsgi:/var/uwsgi
    network_mode: "host"
  noordzee:
    image: naturalis/waarneming-django-2:0.0.1
    restart: unless-stopped
    environment:
      PYTHON_USER: noordzee
    volumes:
      - /home/noordzee/django:/code
      - /home/obs/static:/static
      - /var/uwsgi:/var/uwsgi
    network_mode: "host"
  nederlandzoemt:
    image: naturalis/waarneming-django-3:0.0.1
    restart: unless-stopped
    environment:
      PYTHON_USER: nederlandzoemt
    volumes:
      - /home/nederlandzoemt/django:/code
      - /var/uwsgi:/var/uwsgi
    network_mode: "host"
#  nederlandzoemt:
#    image: naturalis/waarneming-obs:0.0.1
#    volumes:
#      - /home/nederlandzoemt/django:/code
#      - /var/uwsgi:/var/uwsgi
#    networks:
#      - default
