version: '3'

services:
  nginx:
    image: nginx:1.15
    restart: unless-stopped
    network_mode: host
    ports:
      - 80:80
      - 443:443
    extra_hosts:
     - "waarneming.nl:127.0.0.1"
    depends_on:
      - "php"
    volumes:
      - ./nginx/nginx_include:/etc/nginx/include
      - ./nginx/nginx_sites:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx_ssl:/etc/nginx/ssl
      - ./uwsgi:/var/uwsgi
      - ./sock:/sock
      - ${OBS_BASE_PATH:-./obs}/static:/home/obs/static
      - ${NOORDZEE_BASE_PATH:-./noordzee}/static:/home/noordzee/static
      - ${NEDERLANDZOEMT_BASE_PATH:-./nederlandzoemt}/static:/home/nederlandzoemt/static
      - ${PHPAPP_BASE_PATH:-./phpapp}:/home/waarneming
      - ${MEDIA_BASE_PATH:-./media}:/data/waarneming/media

  obs:
    image: naturalis/waarneming-django-2:0.0.1
    restart: unless-stopped
    network_mode: host
    environment:
      PYTHON_USER: obs
    volumes:
      - ${OBS_BASE_PATH:-./obs}/django:/code
      - ${OBS_BASE_PATH:-./obs}/static:/static
      - ./uwsgi:/var/uwsgi

  php:
    image: naturalis/waarneming-php:0.0.1
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${PHPAPP_BASE_PATH:-./phpapp}:/home/waarneming
      - ./sock:/sock

  pgbouncer:
    image:  brainsam/pgbouncer:latest
    restart: unless-stopped
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./sock:/sock
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    env_file:
      - .env

  memcached:
    image:  memcached:1.5.6
    restart: unless-stopped
    network_mode: host

  redis:
    image:  redis:4
    restart: unless-stopped
    network_mode: host


#  noordzee:
#    image: naturalis/waarneming-django-3:0.0.1
#    restart: unless-stopped
#    environment:
#      PYTHON_USER: noordzee
#    volumes:
#      - ${NOORDZEE_BASE_PATH:-./noordzee}/django:/code
#      - ${NOORDZEE_BASE_PATH:-./noordzee}/static:/home/noordzee/static
#      - ./uwsgi:/var/uwsgi

#  nederlandzoemt:
#    image: naturalis/waarneming-django-3:0.0.1
#    restart: unless-stopped
#    environment:
#      PYTHON_USER: nederlandzoemt
#    volumes:
#      - ${NEDERLANDZOEMT_BASE_PATH:-./nederlandzoemt}/django:/code
#      - ${NEDERLANDZOEMT_BASE_PATH:-./nederlandzoemt}/static:/home/nederlandzoemt/static
#      - ./uwsgi:/var/uwsgi

