version: '3'

services:
  web:
    image: naturalis/waarneming-obs:0.0.1
    volumes:
      - /data/obs/django:/code
    networks:
      - default
    ports:
      - "8000:8000"
    command:
      tail -f /dev/null
